name: Update Dataset Count Badge

on:
  push:
    branches: [ main ]

jobs:
  update-badge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install -r requirements.txt || echo "No dependencies"

      - name: Update dataset count JSON
        run: python scripts/update_dataset_count.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add scripts/dataset_count.json
          git commit -m "Update dataset count JSON [skip ci]" || echo "No changes"
          git push
